### ISSUE TITLE
No Lastest Tag

### ISSUE THREAD

**Issue by SquallHalle** [jumanjihouse/docker-testssl#35]
docker pull quay.io/jumanjiman/testssl
Using default tag: latest
Error response from daemon: unknown: Tag latest was deleted or has expired. To pull, revive via time machine

also non herer:
https://quay.io/repository/jumanjiman/testssl?tab=tags

**Comment by jumanjiman** [comment]
@SquallHalle 

Thank you for letting me know!

i've published new, updated images [via CI](https://circleci.com/gh/jumanjihouse/docker-testssl/110) to quay.

![image](https://user-images.githubusercontent.com/332496/70541775-aa252880-1b35-11ea-8297-1fdc5fe3c43c.png)
